const recipes = [
    {
        title: "Middelhavsk Quinoa-bolle",
        cuisine: "Middelhavskjøkken",
        prepTime: "25 minutter",
        ingredients: [
            "1 kopp quinoa",
            "2 kopper vann",
            "1 boks kikerter, avrent",
            "1 agurk, i terninger",
            "2 tomater, i terninger",
            "1 rødløk, finhakket",
            "1/2 kopp Kalamata-oliven",
            "1/2 kopp fetaost",
            "2 ss olivenolje",
            "1 sitron, presset",
            "Fersk persille og mynte",
            "Salt og pepper etter smak"
        ],
        instructions: [
            "Kok quinoa:",
            "• Hell 2 kopper vann i en kjele",
            "• Tilsett 1 kopp quinoa",
            "• Bring til koking på medium varme",
            "• Reduser varmen og la småkoke i 15-20 minutter",
            "• Rør av og til for å unngå at det brenner seg",
            "• Quinoaen er ferdig når den er myk og har små spirer",
            "",
            "Forbered grønnsakene:",
            "• Vask og tørk agurken",
            "• Skjær agurken i terninger på ca. 1 cm",
            "• Vask og skjær tomater i terninger",
            "• Skrell og finhakk rødløken",
            "• Vask og finhakk ferske urter",
            "",
            "Sett sammen salaten:",
            "• Hell den kokte quinoaen i en stor bolle",
            "• La den avkjøles i 5 minutter",
            "• Tilsett alle grønnsakene",
            "• Tilsett avrente kikerter",
            "• Tilsett Kalamata-oliven",
            "",
            "Dress salaten:",
            "• Press saften fra en sitron",
            "• Tilsett 2 ss olivenolje",
            "• Krydre med salt og pepper",
            "• Rør godt sammen",
            "",
            "Servering:",
            "• Topp med fetaost",
            "• Garnér med ferske urter",
            "• Server varm eller kald"
        ]
    },
    {
        title: "Grønnsaksenchiladas",
        cuisine: "Meksikansk",
        prepTime: "30 minutter",
        ingredients: [
            "8 maislefser",
            "2 kopper svarte bønner",
            "1 paprika, i terninger",
            "1 løk, i terninger",
            "1 squash, i terninger",
            "2 kopper enchiladasaus",
            "1 kopp revet ost",
            "1 ts kummin",
            "1 ts chilipulver",
            "Salt og pepper etter smak"
        ],
        instructions: [
            "Forvarm ovnen:",
            "• Sett ovnen på 375°F (190°C)",
            "• La den varme opp i 10 minutter",
            "",
            "Forbered grønnsakene:",
            "• Vask og tørk paprikaen",
            "• Skjær paprika i terninger på ca. 1 cm",
            "• Skrell og skjær løken i terninger",
            "• Vask og skjær squash i terninger",
            "",
            "Stek grønnsakene:",
            "• Varm en stor stekepanne på medium varme",
            "• Tilsett 2 ss olje når pannen er varm",
            "• Fres løken i 3-4 minutter",
            "• Tilsett paprika og squash",
            "• Tilsett kummin og chilipulver",
            "• Stek i 5-7 minutter til grønnsakene er myke",
            "• Tilsett salt og pepper etter smak",
            "",
            "Forbered fyllingen:",
            "• Hell av svarte bønner",
            "• Rør sammen grønnsakene og bønnene",
            "• Smak til med krydder",
            "",
            "Rull enchiladas:",
            "• Varm maislefsene i mikroen i 30 sekunder",
            "• Legg en lefse på et flatt underlag",
            "• Legg 1/8 av fyllingen i midten",
            "• Rull lefsen sammen",
            "• Plasser i ildfast form med sømmen ned",
            "• Gjenta med resten av lefsene",
            "",
            "Fullfør retten:",
            "• Hell enchiladasaus over",
            "• Topp med revet ost",
            "• Stek i 20 minutter",
            "• La stå i 5 minutter før servering"
        ]
    },
    {
        title: "Spinat og Ricotta Cannelloni",
        cuisine: "Italiensk",
        prepTime: "30 minutter",
        ingredients: [
            "12 ferske lasagneplater",
            "500g ricottaost",
            "300g spinat",
            "1 egg",
            "Muskatnøtt",
            "Salt og pepper",
            "Tomatpuré",
            "Mozzarellaost",
            "Fersk basilikum"
        ],
        instructions: [
            "Forvarm ovnen:",
            "• Sett ovnen på 180°C",
            "• La den varme opp i 10 minutter",
            "",
            "Forbered fyllingen:",
            "• Vask og tørk spinaten",
            "• Hakke spinaten grovt",
            "• Bland ricottaost og spinat i en bolle",
            "• Tilsett egget",
            "• Rasp muskatnøtt over",
            "• Krydre med salt og pepper",
            "• Rør godt sammen",
            "",
            "Rull cannelloni:",
            "• Legg en lasagneplate på et flatt underlag",
            "• Fordel 2-3 ss fylling på langs midten",
            "• Rull sammen fra den ene enden",
            "• Plasser i ildfast form med sømmen ned",
            "• Gjenta med resten av platene",
            "",
            "Fullfør retten:",
            "• Hell tomatpuré over cannelloni",
            "• Topp med revet mozzarella",
            "• Stek i 20-25 minutter",
            "• Garnér med fersk basilikum",
            "• La stå i 5 minutter før servering"
        ]
    },
    {
        title: "Grønnsakscurry",
        cuisine: "Indisk",
        prepTime: "25 minutter",
        ingredients: [
            "1 løk, i terninger",
            "2 fedd hvitløk, finhakket",
            "1 ss currypulver",
            "1 ts kummin",
            "1 ts gurkemeie",
            "1 boks kokosmelk",
            "2 kopper blandede grønnsaker",
            "1 kopp kikerter",
            "Fersk koriander",
            "Ris til servering"
        ],
        instructions: [
            "Forbered grønnsakene:",
            "• Vask og tørk alle grønnsaker",
            "• Skrell og terning løken",
            "• Skrell og finhakk hvitløken",
            "• Forbered blandede grønnsaker",
            "",
            "Stek krydder:",
            "• Varm en stor stekepanne på medium varme",
            "• Tilsett 2 ss olje når pannen er varm",
            "• Fres løken i 3-4 minutter til den er myk",
            "• Tilsett hvitløk og stek i 1 minutt",
            "• Tilsett currypulver, kummin og gurkemeie",
            "• Rør og stek i 1-2 minutter til krydderet er godt",
            "",
            "Tilsett grønnsaker:",
            "• Tilsett blandede grønnsaker",
            "• Rør godt sammen med krydderet",
            "• La steke i 5-7 minutter",
            "• Tilsett avrente kikerter",
            "",
            "Fullfør curryen:",
            "• Hell i kokosmelk",
            "• Bring til koking",
            "• Reduser varmen og la småkoke i 10-15 minutter",
            "• Smak til med salt og pepper",
            "",
            "Servering:",
            "• Kok ris etter pakkeinstruksjonene",
            "• Topp curryen med fersk koriander",
            "• Server med varm ris"
        ]
    },
    {
        title: "Gresk Salatbolle",
        cuisine: "Middelhavskjøkken",
        prepTime: "20 minutter",
        ingredients: [
            "2 kopper kokt bulgur",
            "1 agurk, i terninger",
            "2 tomater, i terninger",
            "1 rødløk, i skiver",
            "1/2 kopp Kalamata-oliven",
            "1/2 kopp fetaost",
            "2 ss olivenolje",
            "1 sitron, presset",
            "Tørket oregano",
            "Salt og pepper"
        ],
        instructions: [
            "Kok bulgur:",
            "• Bring 2 kopper vann til koking",
            "• Tilsett 2 kopper bulgur",
            "• Reduser varmen og la småkoke i 15 minutter",
            "• Rør av og til for å unngå at det brenner seg",
            "• La bulguren avkjøles i 10 minutter",
            "",
            "Forbered grønnsakene:",
            "• Vask og tørk agurken",
            "• Skjær agurken i terninger på ca. 1 cm",
            "• Vask og skjær tomater i terninger",
            "• Skrell og skjær rødløk i tynne skiver",
            "",
            "Sett sammen salaten:",
            "• Hell den kokte bulguren i en stor bolle",
            "• Tilsett alle grønnsakene",
            "• Tilsett Kalamata-oliven",
            "• Rør forsiktig sammen",
            "",
            "Dress salaten:",
            "• Press saften fra en sitron",
            "• Tilsett 2 ss olivenolje",
            "• Tilsett tørket oregano",
            "• Krydre med salt og pepper",
            "• Rør godt sammen",
            "",
            "Fullfør retten:",
            "• Topp med fetaost",
            "• Garnér med ekstra oregano",
            "• Server varm eller kald"
        ]
    },
    {
        title: "Vegetarisk Pad Thai",
        cuisine: "Thai",
        prepTime: "25 minutter",
        ingredients: [
            "200g risnudler",
            "2 ss olivenolje",
            "2 egg",
            "1/2 kopp tofu, i terninger",
            "1 gulrot, i strimler",
            "1/2 kopp bønnespirer",
            "2 ss fiskesaus",
            "1 ss tamarindpuré",
            "1/2 kopp mandler, hakket",
            "Fersk koriander og lime"
        ],
        instructions: [
            "Forbered ingrediensene:",
            "• Vask og tørk tofu",
            "• Skjær tofu i terninger på ca. 1 cm",
            "• Skrell og skjær gulrot i tynne strimler",
            "• Vask bønnespirer",
            "• Hakke mandler",
            "• Vask og finhakk koriander",
            "",
            "Kok nudlene:",
            "• Bring en stor kjele vann til koking",
            "• Legg i risnudlene",
            "• Kok i 8-10 minutter",
            "• Hell av vannet",
            "• La nudlene avkjøles",
            "",
            "Stek tofu:",
            "• Varm en stor wok eller stekepanne på høy varme",
            "• Tilsett 1 ss olje",
            "• Stek tofu i 5-7 minutter til gyllen",
            "• Ta ut av pannen og sett til side",
            "",
            "Lage sausen:",
            "• Bland fiskesaus og tamarindpuré i en bolle",
            "• Tilsett 1 ss vann",
            "• Rør godt sammen",
            "",
            "Fullfør retten:",
            "• Varm 1 ss olje i wok-pannen",
            "• Tilsett egg og stek til de er nesten stivnet",
            "• Tilsett nudler og saus",
            "• Rør godt sammen",
            "• Tilsett tofu, gulrot og bønnespirer",
            "• Stek i 2-3 minutter",
            "",
            "Servering:",
            "• Topp med hakket mandler",
            "• Garnér med fersk koriander",
            "• Server med limebåter"
        ]
    },
    {
        title: "Vegetarisk Lasagne",
        cuisine: "Italiensk",
        prepTime: "30 minutter",
        ingredients: [
            "12 lasagneplater",
            "500g ricottaost",
            "300g spinat",
            "1 løk, hakket",
            "2 fedd hvitløk, hakket",
            "1 boks tomatpuré",
            "1 kopp revet mozzarella",
            "1 kopp melk",
            "2 ss olivenolje",
            "Salt og pepper"
        ],
        instructions: [
            "Forvarm ovnen:",
            "• Sett ovnen på 180°C",
            "• La den varme opp i 10 minutter",
            "",
            "Forbered grønnsakene:",
            "• Skrell og finhakk løken",
            "• Skrell og finhakk hvitløken",
            "• Vask og tørk spinaten",
            "• Hakke spinaten grovt",
            "",
            "Lage sausen:",
            "• Varm olje i en kjele",
            "• Fres løk og hvitløk i 3-4 minutter",
            "• Tilsett tomatpuré",
            "• Tilsett melk",
            "• La småkoke i 5 minutter",
            "• Smak til med salt og pepper",
            "",
            "Forbered fyllingen:",
            "• Bland ricottaost og spinat i en bolle",
            "• Tilsett salt og pepper",
            "• Rør godt sammen",
            "",
            "Sett sammen lasagnen:",
            "• Smør en ildfast form med olje",
            "• Legg et lag med lasagneplater",
            "• Fordel 1/3 av fyllingen",
            "• Hell over 1/3 av sausen",
            "• Gjenta lagene to ganger til",
            "• Avslutt med et lag lasagneplater",
            "",
            "Fullfør retten:",
            "• Hell over resten av sausen",
            "• Topp med revet mozzarella",
            "• Stek i 30 minutter",
            "• La stå i 10 minutter før servering"
        ]
    },
    {
        title: "Vegetarisk Tacos",
        cuisine: "Meksikansk",
        prepTime: "25 minutter",
        ingredients: [
            "8 tacoskjell",
            "400g svarte bønner",
            "1 paprika, i strimler",
            "1 løk, hakket",
            "1 tomat, hakket",
            "1 avokado",
            "1/2 kopp maiss",
            "1/2 kopp revet ost",
            "1 ts kummin",
            "1 ts chilipulver",
            "1 lime",
            "Salt og pepper"
        ],
        instructions: [
            "Forbered grønnsakene:",
            "• Vask og tørk paprikaen",
            "• Skjær paprika i tynne strimler",
            "• Skrell og finhakk løken",
            "• Vask og hakke tomaten",
            "• Skrell og terning avokadoen",
            "",
            "Varm tacoskjellene:",
            "• Sett ovnen på 180°C",
            "• Legg tacoskjellene på en bakepapir",
            "• Varm i 5-7 minutter",
            "• Hold varme under servering",
            "",
            "Stek grønnsakene:",
            "• Varm en stor stekepanne på medium varme",
            "• Tilsett 2 ss olje",
            "• Fres løken i 3-4 minutter",
            "• Tilsett paprika og stek i 5 minutter",
            "• Tilsett kummin og chilipulver",
            "• Stek i 2 minutter til",
            "",
            "Forbered bønnene:",
            "• Hell av svarte bønner",
            "• Varm bønnene i en kjele",
            "• Tilsett salt og pepper",
            "• La småkoke i 5 minutter",
            "",
            "Lag guacamole:",
            "• Mos avokadoen med en gaffel",
            "• Press i saften fra halve lime",
            "• Tilsett salt og pepper",
            "• Rør godt sammen",
            "",
            "Sett sammen tacos:",
            "• Legg et tacoskjell på et fat",
            "• Fordel bønner på midten",
            "• Topp med stekte grønnsaker",
            "• Legg på guacamole",
            "• Topp med maiss og ost",
            "",
            "Servering:",
            "• Garnér med fersk koriander",
            "• Server med limebåter",
            "• Tilbehør: salsa og rømme"
        ]
    },
    {
        title: "Middelhavsk Buddha Bowl",
        cuisine: "Middelhavskjøkken",
        prepTime: "20 minutter",
        ingredients: [
            "1 kopp quinoa",
            "1 boks kikerter",
            "1 agurk",
            "2 tomater",
            "1/2 kopp oliven",
            "1/2 kopp fetaost",
            "2 ss olivenolje",
            "1 sitron",
            "Fersk basilikum",
            "Salt og pepper"
        ],
        instructions: [
            "Kok quinoa:",
            "• Bring 2 kopper vann til koking",
            "• Tilsett quinoa",
            "• Reduser varmen og la småkoke i 15 minutter",
            "• La avkjøles i 5 minutter",
            "",
            "Forbered grønnsakene:",
            "• Vask og tørk agurken",
            "• Skjær agurken i terninger",
            "• Vask og skjær tomater",
            "• Vask basilikum",
            "",
            "Sett sammen bowlen:",
            "• Fordel quinoa i bunnen",
            "• Legg på kikerter",
            "• Topp med grønnsaker",
            "• Tilsett oliven og feta",
            "",
            "Dress bowlen:",
            "• Press sitron",
            "• Tilsett olivenolje",
            "• Krydre med salt og pepper",
            "• Garnér med basilikum"
        ]
    },
    {
        title: "Rask Veggie Wok",
        cuisine: "Asiatisk",
        prepTime: "15 minutter",
        ingredients: [
            "200g risnudler",
            "2 ss sesamolje",
            "2 fedd hvitløk",
            "1 gulrot",
            "1 paprika",
            "1/2 kopp bønnespirer",
            "2 ss soyasaus",
            "1 ts ingefær",
            "Fersk koriander"
        ],
        instructions: [
            "Forbered ingrediensene:",
            "• Skrell og finhakk hvitløk",
            "• Skrell og skjær gulrot i strimler",
            "• Skjær paprika i strimler",
            "• Vask bønnespirer",
            "",
            "Kok nudlene:",
            "• Bring vann til koking",
            "• Kok nudlene i 5 minutter",
            "• Hell av vannet",
            "",
            "Wok-grønnsaker:",
            "• Varm sesamolje i wok",
            "• Fres hvitløk og ingefær",
            "• Tilsett gulrot og paprika",
            "• Stek i 3 minutter",
            "",
            "Fullfør retten:",
            "• Tilsett nudler",
            "• Hell over soyasaus",
            "• Tilsett bønnespirer",
            "• Stek i 2 minutter",
            "• Garnér med koriander"
        ]
    },
    {
        title: "Enkel Pasta Primavera",
        cuisine: "Italiensk",
        prepTime: "20 minutter",
        ingredients: [
            "400g pasta",
            "2 kopper blandede grønnsaker",
            "2 fedd hvitløk",
            "2 ss olivenolje",
            "1/2 kopp parmesan",
            "Fersk basilikum",
            "Salt og pepper"
        ],
        instructions: [
            "Kok pasta:",
            "• Bring vann til koking",
            "• Tilsett salt",
            "• Kok pasta etter pakkeinstruksjonene",
            "• Spare litt pastavann",
            "",
            "Forbered grønnsakene:",
            "• Vask og tørk grønnsakene",
            "• Skrell og finhakk hvitløk",
            "• Skjær store grønnsaker i biter",
            "",
            "Stek grønnsakene:",
            "• Varm olje i en stor panne",
            "• Fres hvitløk",
            "• Tilsett grønnsaker",
            "• Stek i 5-7 minutter",
            "",
            "Fullfør retten:",
            "• Hell pasta i pannen",
            "• Tilsett parmesan",
            "• Tilsett pastavann",
            "• Rør godt sammen",
            "• Garnér med basilikum"
        ]
    },
    {
        title: "Meksikansk Quinoa Bowl",
        cuisine: "Meksikansk",
        prepTime: "25 minutter",
        ingredients: [
            "1 kopp quinoa",
            "1 boks svarte bønner",
            "1 maiss",
            "1 tomat",
            "1 avokado",
            "1 lime",
            "1/2 kopp salsa",
            "1 ts kummin",
            "Fersk koriander",
            "Salt og pepper"
        ],
        instructions: [
            "Kok quinoa:",
            "• Bring 2 kopper vann til koking",
            "• Tilsett quinoa og kummin",
            "• Reduser varmen og la småkoke",
            "• La avkjøles",
            "",
            "Forbered grønnsakene:",
            "• Vask og skjær tomat",
            "• Skrell og terning avokado",
            "• Vask koriander",
            "",
            "Varm bønner:",
            "• Hell av bønner",
            "• Varm i en kjele",
            "• Tilsett salt og pepper",
            "",
            "Sett sammen bowlen:",
            "• Fordel quinoa",
            "• Legg på bønner og maiss",
            "• Topp med grønnsaker",
            "• Tilsett salsa",
            "",
            "Fullfør:",
            "• Press lime over",
            "• Garnér med koriander",
            "• Server varm eller kald"
        ]
    },
    {
        title: "Indisk Dahl",
        cuisine: "Indisk",
        prepTime: "30 minutter",
        ingredients: [
            "1 kopp røde linser",
            "1 løk",
            "2 fedd hvitløk",
            "1 ss ingefær",
            "1 ts kummin",
            "1 ts gurkemeie",
            "1 ts koriander",
            "1 boks kokosmelk",
            "Fersk koriander",
            "Ris til servering"
        ],
        instructions: [
            "Forbered ingrediensene:",
            "• Skrell og finhakk løk",
            "• Skrell og finhakk hvitløk",
            "• Skrell og finhakk ingefær",
            "• Vask linsene",
            "",
            "Stek krydder:",
            "• Varm olje i en kjele",
            "• Fres løk i 5 minutter",
            "• Tilsett hvitløk og ingefær",
            "• Tilsett krydder",
            "• Stek i 2 minutter",
            "",
            "Kok linsene:",
            "• Tilsett linser",
            "• Hell i kokosmelk",
            "• Tilsett 2 kopper vann",
            "• Bring til koking",
            "",
            "Fullfør retten:",
            "• Reduser varmen",
            "• La småkoke i 20 minutter",
            "• Rør av og til",
            "• Smak til med salt",
            "",
            "Servering:",
            "• Topp med fersk koriander",
            "• Server med ris"
        ]
    },
    {
        title: "Gresk Pasta",
        cuisine: "Middelhavskjøkken",
        prepTime: "20 minutter",
        ingredients: [
            "400g pasta",
            "2 tomater",
            "1 agurk",
            "1/2 kopp oliven",
            "1/2 kopp fetaost",
            "2 ss olivenolje",
            "1 sitron",
            "Fersk oregano",
            "Salt og pepper"
        ],
        instructions: [
            "Kok pasta:",
            "• Bring vann til koking",
            "• Tilsett salt",
            "• Kok pasta etter pakkeinstruksjonene",
            "• Spare litt pastavann",
            "",
            "Forbered grønnsakene:",
            "• Vask og skjær tomater",
            "• Skjær agurk i terninger",
            "• Vask oregano",
            "",
            "Sett sammen retten:",
            "• Hell pasta i en bolle",
            "• Tilsett grønnsaker",
            "• Tilsett oliven og feta",
            "• Press over sitron",
            "",
            "Dress retten:",
            "• Tilsett olivenolje",
            "• Tilsett salt og pepper",
            "• Rør godt sammen",
            "• Garnér med oregano"
        ]
    },
    {
        title: "Rask Veggie Burger",
        cuisine: "Amerikansk",
        prepTime: "20 minutter",
        ingredients: [
            "1 boks kikerter",
            "1 løk",
            "1 gulrot",
            "1/2 kopp havregryn",
            "1 egg",
            "1 ts kummin",
            "1 ts paprika",
            "4 hamburgerbrød",
            "Salat og tomat",
            "Salt og pepper"
        ],
        instructions: [
            "Forbered ingrediensene:",
            "• Skrell og finhakk løk",
            "• Skrell og rasp gulrot",
            "• Hell av kikerter",
            "• Vask og tørk salat",
            "",
            "Lag burgerblandingen:",
            "• Mos kikerter med en gaffel",
            "• Tilsett løk og gulrot",
            "• Tilsett havregryn",
            "• Tilsett egg",
            "• Tilsett krydder",
            "",
            "Form burgere:",
            "• Bland godt sammen",
            "• Form til 4 burgere",
            "• Trykk flatt",
            "",
            "Stek burgere:",
            "• Varm olje i en panne",
            "• Stek burgere i 4-5 minutter",
            "• Vend og stek på andre siden",
            "",
            "Servering:",
            "• Varm hamburgerbrødene",
            "• Legg på salat og tomat",
            "• Server med pommes frites"
        ]
    },
    {
        title: "Thai Curry Nudler",
        cuisine: "Thai",
        prepTime: "25 minutter",
        ingredients: [
            "200g risnudler",
            "1 boks kokosmelk",
            "2 ss currypasta",
            "1 gulrot",
            "1 paprika",
            "1/2 kopp bønnespirer",
            "1 lime",
            "Fersk koriander",
            "Salt og pepper"
        ],
        instructions: [
            "Forbered grønnsakene:",
            "• Skrell og skjær gulrot i strimler",
            "• Skjær paprika i strimler",
            "• Vask bønnespirer",
            "• Vask koriander",
            "",
            "Kok nudlene:",
            "• Bring vann til koking",
            "• Kok nudlene i 5 minutter",
            "• Hell av vannet",
            "",
            "Lage sausen:",
            "• Varm kokosmelk i en wok",
            "• Tilsett currypasta",
            "• Rør godt sammen",
            "",
            "Fullfør retten:",
            "• Tilsett grønnsaker",
            "• La småkoke i 5 minutter",
            "• Tilsett nudler",
            "• Press over lime",
            "",
            "Servering:",
            "• Garnér med koriander",
            "• Server varm"
        ]
    },
    {
        title: "Middelhavsk Frittata",
        cuisine: "Middelhavskjøkken",
        prepTime: "25 minutter",
        ingredients: [
            "6 egg",
            "1 løk",
            "1 paprika",
            "1 tomat",
            "1/2 kopp oliven",
            "1/2 kopp fetaost",
            "Fersk basilikum",
            "Salt og pepper"
        ],
        instructions: [
            "Forbered grønnsakene:",
            "• Skrell og finhakk løk",
            "• Skjær paprika i terninger",
            "• Skjær tomat i terninger",
            "• Vask basilikum",
            "",
            "Stek grønnsakene:",
            "• Varm olje i en stekepanne",
            "• Fres løk i 3 minutter",
            "• Tilsett paprika",
            "• Stek i 5 minutter",
            "",
            "Forbered eggene:",
            "• Pisk egg i en bolle",
            "• Tilsett salt og pepper",
            "• Tilsett fetaost",
            "",
            "Lage frittata:",
            "• Legg grønnsakene i en ildfast form",
            "• Hell over eggene",
            "• Topp med oliven",
            "• Stek i 20 minutter",
            "",
            "Servering:",
            "• La avkjøles i 5 minutter",
            "• Garnér med basilikum",
            "• Server varm eller kald"
        ]
    },
    {
        title: "Rask Veggie Stir-Fry",
        cuisine: "Asiatisk",
        prepTime: "15 minutter",
        ingredients: [
            "2 kopper ris",
            "2 ss sesamolje",
            "2 fedd hvitløk",
            "1 gulrot",
            "1 paprika",
            "1/2 kopp bønnespirer",
            "2 ss soyasaus",
            "1 ts ingefær",
            "Fersk koriander"
        ],
        instructions: [
            "Kok ris:",
            "• Bring 4 kopper vann til koking",
            "• Tilsett ris",
            "• Reduser varmen og la småkoke",
            "",
            "Forbered grønnsakene:",
            "• Skrell og finhakk hvitløk",
            "• Skrell og skjær gulrot i strimler",
            "• Skjær paprika i strimler",
            "• Vask bønnespirer",
            "",
            "Stek grønnsakene:",
            "• Varm sesamolje i wok",
            "• Fres hvitløk og ingefær",
            "• Tilsett gulrot og paprika",
            "• Stek i 3 minutter",
            "",
            "Fullfør retten:",
            "• Tilsett bønnespirer",
            "• Hell over soyasaus",
            "• Stek i 2 minutter",
            "",
            "Servering:",
            "• Server med varm ris",
            "• Garnér med koriander"
        ]
    },
    {
        title: "Rask Veggie Ramen",
        cuisine: "Japansk",
        prepTime: "15 minutter",
        category: "rask",
        ingredients: [
            "2 pakker instant ramen",
            "1/2 kopp tofu",
            "1/2 kopp bønnespirer",
            "1/2 kopp maiss",
            "1/2 kopp vårløk",
            "1 egg",
            "2 ss soyasaus",
            "1 ts sesamolje",
            "Fersk koriander"
        ],
        instructions: [
            "Forbered ingrediensene:",
            "• Skjær tofu i terninger",
            "• Vask bønnespirer",
            "• Skjær vårløk i strimler",
            "• Vask koriander",
            "",
            "Kok ramen:",
            "• Bring vann til koking",
            "• Tilsett nudlene",
            "• Kok i 3 minutter",
            "",
            "Tilsett grønnsaker:",
            "• Tilsett tofu",
            "• Tilsett bønnespirer",
            "• Tilsett maiss",
            "• La småkoke i 2 minutter",
            "",
            "Fullfør retten:",
            "• Tilsett egg",
            "• Tilsett soyasaus",
            "• Tilsett sesamolje",
            "• Topp med vårløk og koriander"
        ]
    },
    {
        title: "Luksuriøs Helgepasta",
        cuisine: "Italiensk",
        prepTime: "30 minutter",
        category: "helgekos",
        ingredients: [
            "400g fersk pasta",
            "2 kopper sopp",
            "1/2 kopp parmesan",
            "1/2 kopp mascarpone",
            "2 fedd hvitløk",
            "1/2 kopp pinjekjerner",
            "Fersk timian",
            "Salt og pepper"
        ],
        instructions: [
            "Forbered ingrediensene:",
            "• Vask og skjær sopp",
            "• Skrell og finhakk hvitløk",
            "• Vask timian",
            "• Rist pinjekjerner",
            "",
            "Stek sopp:",
            "• Varm olje i en stor panne",
            "• Fres hvitløk",
            "• Tilsett sopp",
            "• Stek i 8-10 minutter",
            "",
            "Kok pasta:",
            "• Bring vann til koking",
            "• Tilsett salt",
            "• Kok pasta i 3-4 minutter",
            "• Spare litt pastavann",
            "",
            "Lage sausen:",
            "• Tilsett mascarpone til soppen",
            "• Tilsett parmesan",
            "• Tilsett pastavann",
            "• La småkoke i 2 minutter",
            "",
            "Fullfør retten:",
            "• Hell pasta i sausen",
            "• Tilsett pinjekjerner",
            "• Garnér med timian",
            "• Server med ekstra parmesan"
        ]
    },
    {
        title: "Rask Veggie Pizza",
        cuisine: "Italiensk",
        prepTime: "20 minutter",
        category: "rask",
        ingredients: [
            "2 pitabrød",
            "1/2 kopp tomatpuré",
            "1/2 kopp revet ost",
            "1 paprika",
            "1/2 løk",
            "1/2 kopp sopp",
            "Fersk basilikum",
            "Salt og pepper"
        ],
        instructions: [
            "Forbered grønnsakene:",
            "• Vask og skjær paprika",
            "• Skrell og skjær løk",
            "• Vask og skjær sopp",
            "• Vask basilikum",
            "",
            "Forvarm ovnen:",
            "• Sett ovnen på 200°C",
            "• La den varme opp i 5 minutter",
            "",
            "Sett sammen pizza:",
            "• Smør pitabrød med tomatpuré",
            "• Fordel grønnsaker",
            "• Topp med ost",
            "• Krydre med salt og pepper",
            "",
            "Stek pizza:",
            "• Legg på bakepapir",
            "• Stek i 8-10 minutter",
            "• Garnér med basilikum"
        ]
    },
    {
        title: "Luksuriøs Helgequiche",
        cuisine: "Fransk",
        prepTime: "45 minutter",
        category: "helgekos",
        ingredients: [
            "1 paibunn",
            "6 egg",
            "1/2 kopp fløte",
            "1/2 kopp revet ost",
            "1/2 kopp sopp",
            "1/2 kopp asparges",
            "1/2 løk",
            "Muskatnøtt",
            "Salt og pepper"
        ],
        instructions: [
            "Forvarm ovnen:",
            "• Sett ovnen på 180°C",
            "• La den varme opp i 10 minutter",
            "",
            "Forbered grønnsakene:",
            "• Vask og skjær sopp",
            "• Vask og skjær asparges",
            "• Skrell og finhakk løk",
            "",
            "Stek grønnsakene:",
            "• Varm olje i en panne",
            "• Fres løk i 3 minutter",
            "• Tilsett sopp og asparges",
            "• Stek i 5 minutter",
            "",
            "Forbered eggemassen:",
            "• Pisk egg og fløte",
            "• Tilsett revet ost",
            "• Rasp muskatnøtt",
            "• Krydre med salt og pepper",
            "",
            "Fullfør quichen:",
            "• Legg grønnsakene i paibunnen",
            "• Hell over eggemassen",
            "• Stek i 30 minutter",
            "• La stå i 10 minutter"
        ]
    },
    {
        title: "Rask Veggie Wrap",
        cuisine: "Meksikansk",
        prepTime: "15 minutter",
        category: "rask",
        ingredients: [
            "2 tortilla",
            "1/2 kopp hummus",
            "1/2 kopp blandede grønnsaker",
            "1/2 avokado",
            "1/2 kopp maiss",
            "1/2 kopp bønnespirer",
            "Fersk koriander",
            "Salt og pepper"
        ],
        instructions: [
            "Forbered grønnsakene:",
            "• Vask og tørk grønnsaker",
            "• Skrell og skjær avokado",
            "• Vask bønnespirer",
            "• Vask koriander",
            "",
            "Varm tortilla:",
            "• Varm tortilla i mikroen",
            "• Hold varme under servering",
            "",
            "Sett sammen wrap:",
            "• Smør hummus på tortilla",
            "• Legg på grønnsaker",
            "• Tilsett avokado",
            "• Tilsett maiss",
            "• Tilsett bønnespirer",
            "",
            "Rull wrap:",
            "• Fold inn sidene",
            "• Rull sammen",
            "• Skjær på skrå",
            "• Garnér med koriander"
        ]
    },
    {
        title: "Luksuriøs Helgepasta Alfredo",
        cuisine: "Italiensk",
        prepTime: "30 minutter",
        category: "helgekos",
        ingredients: [
            "400g fersk pasta",
            "2 kopper fløte",
            "1 kopp parmesan",
            "2 fedd hvitløk",
            "1/2 kopp pinjekjerner",
            "Fersk persille",
            "Muskatnøtt",
            "Salt og pepper"
        ],
        instructions: [
            "Forbered ingrediensene:",
            "• Skrell og finhakk hvitløk",
            "• Vask persille",
            "• Rist pinjekjerner",
            "",
            "Kok pasta:",
            "• Bring vann til koking",
            "• Tilsett salt",
            "• Kok pasta i 3-4 minutter",
            "• Spare litt pastavann",
            "",
            "Lage sausen:",
            "• Varm fløte i en kjele",
            "• Fres hvitløk",
            "• Tilsett parmesan",
            "• Rasp muskatnøtt",
            "• La småkoke i 5 minutter",
            "",
            "Fullfør retten:",
            "• Hell pasta i sausen",
            "• Tilsett pastavann",
            "• Tilsett pinjekjerner",
            "• Garnér med persille",
            "• Server med ekstra parmesan"
        ]
    },
    {
        title: "Rask Veggie Nudelsalat",
        cuisine: "Asiatisk",
        prepTime: "15 minutter",
        category: "rask",
        ingredients: [
            "200g risnudler",
            "1/2 kopp bønnespirer",
            "1/2 kopp gulrot",
            "1/2 kopp paprika",
            "2 ss sesamolje",
            "2 ss soyasaus",
            "1 lime",
            "Fersk koriander"
        ],
        instructions: [
            "Kok nudlene:",
            "• Bring vann til koking",
            "• Kok nudlene i 5 minutter",
            "• Hell av vannet",
            "• La avkjøles",
            "",
            "Forbered grønnsakene:",
            "• Skrell og skjær gulrot i strimler",
            "• Skjær paprika i strimler",
            "• Vask bønnespirer",
            "• Vask koriander",
            "",
            "Lage dressingen:",
            "• Press lime",
            "• Tilsett sesamolje",
            "• Tilsett soyasaus",
            "• Rør godt sammen",
            "",
            "Sett sammen salaten:",
            "• Bland nudler og grønnsaker",
            "• Hell over dressing",
            "• Rør godt sammen",
            "• Garnér med koriander"
        ]
    },
    {
        title: "Luksuriøs Helgecurry",
        cuisine: "Thai",
        prepTime: "40 minutter",
        category: "helgekos",
        ingredients: [
            "1 boks kokosmelk",
            "2 ss rød currypasta",
            "1/2 kopp tofu",
            "1/2 kopp bambusskudd",
            "1/2 kopp sopp",
            "1/2 kopp bønnespirer",
            "1 lime",
            "Fersk koriander",
            "1/2 kopp cashewnøtter"
        ],
        instructions: [
            "Forbered ingrediensene:",
            "• Skjær tofu i terninger",
            "• Vask bambusskudd",
            "• Vask og skjær sopp",
            "• Vask bønnespirer",
            "• Vask koriander",
            "",
            "Stek tofu:",
            "• Varm olje i en wok",
            "• Stek tofu i 5 minutter",
            "• Ta ut og sett til side",
            "",
            "Lage curryen:",
            "• Varm kokosmelk i wok",
            "• Tilsett currypasta",
            "• Rør godt sammen",
            "• La småkoke i 5 minutter",
            "",
            "Tilsett grønnsaker:",
            "• Tilsett bambusskudd",
            "• Tilsett sopp",
            "• La småkoke i 5 minutter",
            "• Tilsett tofu",
            "",
            "Fullfør retten:",
            "• Tilsett bønnespirer",
            "• Press lime",
            "• Topp med cashewnøtter",
            "• Garnér med koriander"
        ]
    },
    {
        title: "Rask Veggie Risotto",
        cuisine: "Italiensk",
        prepTime: "20 minutter",
        category: "rask",
        ingredients: [
            "2 kopper ris",
            "1 løk",
            "2 fedd hvitløk",
            "1/2 kopp parmesan",
            "1/2 kopp hvitvin",
            "1/2 kopp erter",
            "Fersk basilikum",
            "Salt og pepper"
        ],
        instructions: [
            "Forbered ingrediensene:",
            "• Skrell og finhakk løk",
            "• Skrell og finhakk hvitløk",
            "• Vask basilikum",
            "",
            "Stek ris:",
            "• Varm olje i en kjele",
            "• Fres løk og hvitløk",
            "• Tilsett ris",
            "• Stek i 2 minutter",
            "",
            "Kok risotto:",
            "• Tilsett hvitvin",
            "• La vin fordampe",
            "• Tilsett varm buljong",
            "• Rør av og til",
            "",
            "Fullfør retten:",
            "• Tilsett erter",
            "• Tilsett parmesan",
            "• Rør godt sammen",
            "• Garnér med basilikum"
        ]
    },
    {
        title: "Luksuriøs Helgepizza",
        cuisine: "Italiensk",
        prepTime: "45 minutter",
        category: "helgekos",
        ingredients: [
            "1 pizzadeig",
            "1/2 kopp tomatpuré",
            "1/2 kopp mozzarella",
            "1/2 kopp parmesan",
            "1/2 kopp sopp",
            "1/2 kopp artisjokk",
            "1/2 kopp oliven",
            "Fersk basilikum",
            "Salt og pepper"
        ],
        instructions: [
            "Forvarm ovnen:",
            "• Sett ovnen på 250°C",
            "• La den varme opp i 15 minutter",
            "",
            "Forbered ingrediensene:",
            "• Vask og skjær sopp",
            "• Vask artisjokk",
            "• Vask basilikum",
            "• Rev osten",
            "",
            "Rull ut deigen:",
            "• Rull ut på bakepapir",
            "• Trykk ut kanter",
            "• La hvile i 10 minutter",
            "",
            "Sett sammen pizza:",
            "• Smør med tomatpuré",
            "• Fordel mozzarella",
            "• Legg på grønnsaker",
            "• Topp med parmesan",
            "",
            "Stek pizza:",
            "• Stek i 12-15 minutter",
            "• Garnér med basilikum",
            "• La stå i 5 minutter"
        ]
    },
    {
        title: "5-minutters Sjokoladepudding",
        prepTime: "5 minutter",
        cuisine: "Dessert",
        category: "dessert",
        ingredients: [
            "2 dl melk",
            "1 dl kremfløte",
            "100g mørk sjokolade",
            "1 ss sukker",
            "1 ts vaniljesukker",
            "1 ss maizena"
        ],
        instructions: [
            "Forbered ingrediensene:",
            "• Finhakk sjokoladen",
            "• Bland maizena med litt kald melk",
            "Lag puddingen:",
            "• Varm melk og kremfløte i en kjele",
            "• Rør inn maizena-blandingen",
            "• Tilsett sjokolade og rør til den er smeltet",
            "• Tilsett sukker og vaniljesukker",
            "• La koke under omrøring til puddingen tykner",
            "Servering:",
            "• Hell i små glass eller skåler",
            "• La avkjøle i 5 minutter",
            "• Topp med ferske bær eller sjokoladerasp"
        ]
    },
    {
        title: "Rask Ferskenmousse",
        prepTime: "10 minutter",
        cuisine: "Dessert",
        category: "dessert",
        ingredients: [
            "1 boks hermetisk fersken (400g)",
            "2 dl kremfløte",
            "1 pakke vaniljepudding",
            "1 ss sukker",
            "Ferske mynte for garnityr"
        ],
        instructions: [
            "Forbered fersken:",
            "• Hell av fersken og mos den med en gaffel",
            "Lag moussen:",
            "• Pisk kremfløte til den er stiv",
            "• Rør sammen ferskenmos og vaniljepudding",
            "• Fold inn den piskede kremfløten",
            "• Tilsett sukker etter smak",
            "Servering:",
            "• Hell i glass eller skåler",
            "• Garnér med fersk mynte",
            "• Server kald"
        ]
    },
    {
        title: "Express Tiramisu",
        prepTime: "15 minutter",
        cuisine: "Dessert",
        category: "dessert",
        ingredients: [
            "1 pakke ladyfingers",
            "2 dl sterk kaffe",
            "250g mascarpone",
            "2 dl kremfløte",
            "2 ss sukker",
            "1 ts vaniljesukker",
            "Kakao for dryssing"
        ],
        instructions: [
            "Forbered kaffen:",
            "• Lag sterk kaffe og la den avkjøle",
            "Lag kremen:",
            "• Pisk kremfløte til den er stiv",
            "• Rør sammen mascarpone og sukker",
            "• Fold inn den piskede kremfløten",
            "Sett sammen:",
            "• Dypp ladyfingers i kaffen",
            "• Legg et lag med krem",
            "• Gjenta lagene",
            "• Dryss over kakao",
            "• La stå i kjøleskapet i 30 minutter"
        ]
    },
    {
        title: "Rask Fruktpai",
        prepTime: "20 minutter",
        cuisine: "Dessert",
        category: "dessert",
        ingredients: [
            "1 pakke ferdig paibunn",
            "2 dl kremfløte",
            "1 pakke vaniljepudding",
            "Ferske bær eller frukt",
            "1 ss sukker"
        ],
        instructions: [
            "Forbered paibunnen:",
            "• Bak paibunnen etter pakkeanvisning",
            "• La avkjøle",
            "Lag fyllingen:",
            "• Lag vaniljepudding etter anvisning",
            "• La avkjøle",
            "Sett sammen:",
            "• Hell puddingen i paibunnen",
            "• Topp med ferske bær eller frukt",
            "• Server kald"
        ]
    },
    {
        title: "3-ingredienser Sjokoladekake",
        prepTime: "25 minutter",
        cuisine: "Dessert",
        category: "dessert",
        ingredients: [
            "3 egg",
            "150g mørk sjokolade",
            "1 ss mel",
            "1 ss sukker (valgfritt)"
        ],
        instructions: [
            "Forbered ovnen:",
            "• Forvarm ovnen til 175°C",
            "• Smør en liten kakeform",
            "Lag kaken:",
            "• Smelt sjokoladen",
            "• Rør sammen egg og mel",
            "• Bland inn smeltet sjokolade",
            "• Tilsett sukker hvis ønskelig",
            "Baking:",
            "• Hell røren i formen",
            "• Bak i 15-20 minutter",
            "• La avkjøle før servering"
        ]
    },
    {
        title: "Rask Yogurtis",
        prepTime: "10 minutter",
        cuisine: "Dessert",
        category: "dessert",
        ingredients: [
            "2 dl gresk yoghurt",
            "1 dl kremfløte",
            "2 ss honning",
            "1 ts vaniljesukker",
            "Ferske bær"
        ],
        instructions: [
            "Forbered ingrediensene:",
            "• Rør sammen yoghurt og kremfløte",
            "• Tilsett honning og vaniljesukker",
            "• Rør godt",
            "Servering:",
            "• Hell i glass eller skåler",
            "• Topp med ferske bær",
            "• Server med en kjepp"
        ]
    },
    {
        title: "Express Eplekompott",
        prepTime: "15 minutter",
        cuisine: "Dessert",
        category: "dessert",
        ingredients: [
            "4 epler",
            "2 ss sukker",
            "1 ts kanel",
            "1 dl vann",
            "Vaniljeis til servering"
        ],
        instructions: [
            "Forbered eplene:",
            "• Skrell og del eplene i biter",
            "Lag kompotten:",
            "• Legg eplebiter i en kjele",
            "• Tilsett vann og sukker",
            "• La koke under omrøring i 10 minutter",
            "• Tilsett kanel",
            "Servering:",
            "• La avkjøle litt",
            "• Server med vaniljeis"
        ]
    },
    {
        title: "Rask Bananpudding",
        prepTime: "10 minutter",
        cuisine: "Dessert",
        category: "dessert",
        ingredients: [
            "2 bananer",
            "1 dl kremfløte",
            "1 pakke vaniljepudding",
            "1 ss sukker",
            "Kjeks for topping"
        ],
        instructions: [
            "Forbered bananene:",
            "• Mos bananene med en gaffel",
            "Lag puddingen:",
            "• Lag vaniljepudding etter anvisning",
            "• Rør inn bananmos",
            "• Tilsett sukker etter smak",
            "Servering:",
            "• Hell i glass",
            "• Topp med knuste kjeks",
            "• Server kald"
        ]
    },
    {
        title: "Express Sjokolademousse",
        prepTime: "10 minutter",
        cuisine: "Dessert",
        category: "dessert",
        ingredients: [
            "200g mørk sjokolade",
            "2 dl kremfløte",
            "2 egg",
            "1 ss sukker",
            "Ferske bær"
        ],
        instructions: [
            "Forbered sjokoladen:",
            "• Smelt sjokoladen",
            "Lag moussen:",
            "• Pisk kremfløte til den er stiv",
            "• Rør sammen egg og sukker",
            "• Bland inn smeltet sjokolade",
            "• Fold inn den piskede kremfløten",
            "Servering:",
            "• Hell i glass",
            "• Topp med ferske bær",
            "• La stå i kjøleskapet i 30 minutter"
        ]
    },
    {
        title: "Rask Fruktkake",
        prepTime: "20 minutter",
        cuisine: "Dessert",
        category: "dessert",
        ingredients: [
            "1 pakke ferdig kakebunn",
            "2 dl kremfløte",
            "1 pakke vaniljepudding",
            "Assorterte ferske frukter",
            "1 ss sukker"
        ],
        instructions: [
            "Forbered kakebunnen:",
            "• Bak kakebunnen etter pakkeanvisning",
            "• La avkjøle",
            "Lag fyllingen:",
            "• Lag vaniljepudding etter anvisning",
            "• La avkjøle",
            "Sett sammen:",
            "• Hell puddingen på kakebunnen",
            "• Dekk med ferske frukter",
            "• Server kald"
        ]
    }
]; 